// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJUUoEEDoAWJECPSQBWGAvJCNY04NSHSs',
    appId: '1:111899267383:web:3b69ae02eb3bcd1937cab2',
    messagingSenderId: '111899267383',
    projectId: 'florista-efb35',
    authDomain: 'florista-efb35.firebaseapp.com',
    storageBucket: 'florista-efb35.firebasestorage.app',
    measurementId: 'G-YNHTLZ2T4Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjrGQt-vRcXQjsIgSGEw8ppz0irkUApsM',
    appId: '1:111899267383:android:c7842c5a6514d70a37cab2',
    messagingSenderId: '111899267383',
    projectId: 'florista-efb35',
    storageBucket: 'florista-efb35.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJUUoEEDoAWJECPSQBWGAvJCNY04NSHSs',
    appId: '1:111899267383:web:8eb48d5d2da9deef37cab2',
    messagingSenderId: '111899267383',
    projectId: 'florista-efb35',
    authDomain: 'florista-efb35.firebaseapp.com',
    storageBucket: 'florista-efb35.firebasestorage.app',
    measurementId: 'G-6Z9WT78B6Z',
  );

}